### ISSUE TITLE
Feature request: Changing preview behavior

### ISSUE THREAD

**Issue by WolframRhodium** [dubhater/Wobbly#2]
In Wobbly v4, when I pressed "**s**"(Cycle the current frame's match) in preview mode 1(the frame number **before** decimation was bold), the frame **would** refresh instantly. That's nice.
However,  in preview mode 2(the frame number **after** decimation was bold), the frame **would not** refresh instantly. The only way I found I can preview the changed frame is to toggle the preview mode to 1 and then toggle back to 2, which makes me in trouble every time.
Could you change the preview behavior of preview mode 2, so that it can refresh instantly after any operation, as mode 1 behaves now?

**Comment by dubhater** [comment]
Maybe. I predict it won't happen soon.

**Comment by WolframRhodium** [comment]
Thanks

**Comment by WolframRhodium** [comment]
I came across the same problem that failed to make Left and Right arrows to work, which had been reported in Doom9(http://forum.doom9.org/showthread.php?p=1774361#post1774361).

I'm using Windows 10, Vapoursynth R32 x64, Wobbly v4.

I can reproduce the problem anytime with following steps:

1. double click on **Wobbly.exe**
2. click "**Project**" at Menu
3. click "**open video**" ("open project" has same problem)
4. choose .d2v file (or .VOB, .m2ts, etc)
5. **Left** and **Right** arrows broke down on **Wobbly**, but most of other keys worked

By default, Left and Right arrows are used to jump to previous or next frames.

If I change the shortcuts, for example, "**[**", to "Jump 1 frame back", this feature **worked**.
And, if I set "**Left**" back to "Jump 1 frame back", it **broke down** again.

Similarly, if I set "**Left**" or "**Right**" to other places, like "Open project", it still **broke down**.

The problem seems _**only happened on Left and Right arrows**_, after using Wobbly and Wibbly for some times, because I can use them normally 4 days earlier, when I was the first time using Wobbly.

**Comment by dubhater** [comment]
> Could you change the preview behavior of preview mode 2, so that it can refresh instantly after any operation, as mode 1 behaves now?

After years of waiting, I implemented this request.
