### ISSUE TITLE
Wibbly fails with Python error

### ISSUE THREAD

**Issue by mia-0** [dubhater/Wobbly#5]
Platform: openSUSE Tumbleweed
Python: 3.7.2
VapourSynth: r45
Wobbly: a7b0ef165201f30e2a30c273cbaa8472d1aa1b1d

Loading any video file, I get an error message like this:

```
Failed to evaluate display script. Error message:
Python exception: positional argument follows keyword argument (VIDEO_TS, line 20)


Traceback (most recent call last):
  File "src/cython/vapoursynth.pyx", line 1924, in vapoursynth.vpy_evaluateScript
  File "/stuff/projects/fagsub/szs/disc1/VIDEO_TS", line 20
    
    ^
SyntaxError: positional argument follows keyword argument
```

**Comment by dubhater** [comment]
Is there a single quote in the file name?

**Comment by lachs0r** [comment]
On Thursday, February 14, 2019 2:26:00 PM CET dubhater wrote:
> Is there a single quote in the file name?

No.

**Comment by dubhater** [comment]
Perhaps you could use gdb to find out what the script looks like?

**Comment by dubhater** [comment]
Break here: https://github.com/dubhater/Wobbly/blob/master/src/wibbly/WibblyWindow.cpp#L1259

**Comment by WeebDataHoarder** [comment]
I have created #11 to fix the locale issue @mia-0, an alternative being setting your locale to `C` for everything when calling the program.
