### ISSUE TITLE
Wibbly freezes when seeking

### ISSUE THREAD

**Issue by no1d** [dubhater/Wobbly#8]
I believe there is a deadlock between **displayFrame** and **messageHandler**.
To reproduce set max cache to a very low value and try seeking with arrow keys to trigger VS memory limit message.
Changing connection type from **BlockingQueuedConnection** to **QueuedConnection** in **messageHandler** seems to fix it.

**Comment by dubhater** [comment]
If you send a pull request I'll merge it.
